### only uncomment the profiles you are able to support :) 
default:
  outputs:
          
    bigquery:    
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: testxdb
      threads: 1
      keyfile: /app/keyfile.json
      timeout_seconds: 300
      priority: interactive
      retries: 1

    postgres:
      type: postgres
      threads: 1
      host: testxdb_postgres
      port: 5432
      user: testxdb
      pass: testxdb
      dbname: testxdb
      schema: prod

#    redshift:
#      type: redshift
#      threads: 1
#      host: 127.0.0.1
#      port: 5439
#      user: alice
#      pass: pa55word
#      dbname: warehouse
#      schema: dbt_alice

    snowflake:
      type: snowflake
      threads: 1
      account: 
      user: "{{env_var('SNOWFLAKE_USER')}}"
      role: sysadmin
      password: "{{env_var('SNOWFLAKE_PASSWORD')}}"
      database: "{{env_var('SNOWFLAKE_DATABASE')}}"
      schema: test_xdb
      warehouse: xsmall

  target: postgres
