
version: 2

models:
    - name: regexp_test
      description: "tests regexp"
      columns:
          - name: banana_domain
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing', 'https://www.banana.com?query=thing']
          - name: landing_page_url
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing']

    - name: any_value_test
      description: "tests returns any value"
      columns:
          - name: value_col
            tests:
              - not_null

    - name: using_test
      description: "tests using join clause"
      columns:
          - name: number_of_rows
            tests:
              - accepted_values:
                   values: [1]
                   quote: false

    - name: aggregate_strings_test
      description: "tests aggregate_strings macro"
      columns:
          - name: value_col
            tests:
              - not_null
              - accepted_values:
                   values: ["apple,tractor,zebra"]
                   quote: true

    - name: datediff_test
      description: "tests datediff macro"
      columns:
          - name: one_day_diff
            tests:
              - not_null
              - accepted_values:
                   values: [1]
                   quote: false
          - name: two_week_diff
            tests:
              - not_null
              - accepted_values:
                   values: [2]
                   quote: false
          - name: three_month_diff
            tests:
              - not_null
              - accepted_values:
                   values: [3]
                   quote: false
          - name: four_year_diff
            tests:
              - not_null
              - accepted_values:
                   values: [4]
                   quote: false
          - name: five_quarter_diff
            tests:
              - not_null
              - accepted_values:
                   values: [5]
                   quote: false
          - name: twentyfive_hour_diff
            tests:
              - not_null
              - accepted_values:
                  values: [25]
                  quote: false
          - name: fifty_minute_diff
            tests:
              - not_null
              - accepted_values:
                  values: [50]
                  quote: false
          - name: sixty_second_diff
            tests:
              - not_null
              - accepted_values:
                  values: [60]
                  quote: false

    - name: cast_timestamp_test
      description: "tests that timestamps are correctly cast (postgres, snowflake only for ntz)."
      columns:
          - name: date_tz
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31 19:00:00','2020-01-01 00:00:00+00']
                   quote: true
          - name: tstamp_tz
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 15:20:20', '2020-01-01 20:20:20+00']
                   quote: true
          - name: date_ntz
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 00:00:00']
                   quote: true
          - name: tstamp_ntz
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 20:20:20']
                   quote: true
    - name: interval_to_timestamp_test
      description: "tests interval_to_timestamp macro"
      columns:
          - name: three_seconds_second
            tests:
              - not_null
              - accepted_values:
                   values: ['00:00:03']
                   quote: true
          - name: three_minutes_second
            tests:
              - not_null
              - accepted_values:
                   values: ['00:03:00']
                   quote: true
          - name: three_hours_second
            tests:
              - not_null
              - accepted_values:
                   values: ['03:00:00']
                   quote: true
          - name: thirty_three_hours_thirty_minutes_three_seconds_second
            tests:
              - not_null
              - accepted_values:
                   values: ['33:30:03']
                   quote: true
          - name: three_minutes_minute
            tests:
              - not_null
              - accepted_values:
                   values: ['00:03:00']
                   quote: true
          - name: three_hours_minute
            tests:
              - not_null
              - accepted_values:
                   values: ['03:00:00']
                   quote: true
          - name: thirty_three_hours_thirty_minutes_minute
            tests:
              - not_null
              - accepted_values:
                   values: ['33:30:00']
                   quote: true

    - name: regexp_count_test
      description: "tests that regex_count counts the number of match instances in a string."
      columns:
          - name: finds_one
            tests:
              - not_null
              - accepted_values:
                   values: [1]
                   quote: false
          - name: finds_three
            tests:
              - not_null
              - accepted_values:
                   values: [3]
                   quote: false
          - name: finds_four
            tests:
              - not_null
              - accepted_values:
                   values: [4]
                   quote: false

    - name: dateadd_test
      description: "adds dates"
      columns:
          - name: one_day_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-02']
                   quote: true
          - name: one_day_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31']
                   quote: true
          - name: one_week_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-08']
                   quote: true
          - name: one_week_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-25']
                   quote: true
          - name: one_month_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-02-01']
                   quote: true
          - name: one_month_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-01']
                   quote: true
          - name: one_year_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2021-01-01']
                   quote: true
          - name: one_year_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-01-01']
                   quote: true
    - name: timeadd_test
      description: "adds time"
      columns:
          - name: one_second_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 00:00:01']
                   quote: true
          - name: one_second_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31 23:59:59']
                   quote: true
          - name: one_minute_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 00:01:00']
                   quote: true
          - name: one_minute_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31 23:59:00']
                   quote: true
          - name: one_hour_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-01 01:00:00']
                   quote: true
          - name: one_hour_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31 23:00:00']
                   quote: true
    - name: like_any_test
      description: "do like any"
      columns:
        - name: test_name
          tests:
            - not_null
            - accepted_values:
                values: ['test_1', 'test_2', 'test_11', 'test_22']
                quote: true
