version: "3.5"

services:
  testxdb_postgres:
    image: postgres:12
    hostname: testxdb_postgres
    environment:
      POSTGRES_PASSWORD: testxdb
      POSTGRES_USER: testxdb
      POSTGRES_DB: testxdb
    ports:
      - "5432:5432"

  testxdb:
    image: testxdb
    working_dir: /app
    environment:
      PATH: "/app:${PATH}"
      SNOWFLAKE_USERNAME: "${SNOWFLAKE_USERNAME}"
      SNOWFLAKE_PASSWORD: "${SNOWFLAKE_PASSWORD}"
      SNOWFLAKE_ACCOUNT: "${SNOWFLAKE_ACCOUNT}"
      SNOWFLAKE_DATABASE: XDB_TEST
      SNOWFLAKE_ROLE: XDB_ROLE
      BIGQUERY_PROJECT: "${BIGQUERY_PROJECT}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_xdb/:/app
      - ./:/dbt-xdb
    command: tail -f /dev/null
